version: "2"
services:
  wordpress-db:
    image: mariadb
    ports:
      - "8082:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ChangeMeIfYouWant
  wordpress:
    image: wordpress
    volumes:
      - ./wordpress:/var/www/html
    ports:
      - "8080:80"
    links:
      - wordpress-db:mysql
    environment:
      WORDPRESS_DB_PASSWORD: ChangeMeIfYouWant
